# ===== Pharma Hub - Dev Profile =====
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pharmahub_dev
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.max-size=5

# Log
quarkus.log.level=DEBUG
quarkus.log.console.json=false
quarkus.log.category."com.rmfarma".level=DEBUG

# API Keys dev
queryhub.security.api-keys.dev-client=dev-api-key-123
queryhub.security.api-keys.test-client=test-api-key-456

