# ===== Pharma Hub - Prod Profile =====
quarkus.datasource.jdbc.url=${DATABASE_URL}
quarkus.datasource.username=${DATABASE_USER}
quarkus.datasource.password=${DATABASE_PASSWORD}
quarkus.datasource.jdbc.max-size=10
quarkus.datasource.jdbc.min-size=2

# Log
quarkus.log.level=INFO
quarkus.log.console.json=true
quarkus.log.category."com.rmfarma".level=INFO

# API Keys via env vars
queryhub.security.api-keys.pharma-app=${API_KEY_PHARMA_APP}
queryhub.security.api-keys.admin-dashboard=${API_KEY_ADMIN_DASHBOARD}

